The Data set consists of 1200 records of Cardiovascular ECGs where each of the 300 records belongs to one ailment, in such a way 4 ailments have been considered. The original signals are taken from the MIT-BIH physio-net Database. **One ailment is the MIT-BIH Arrhythmia Database, the other is BIDMC Congestive Heart Failure Database and MIT-BIH Atrial Fibrillation Database and finally MIT-BIH Normal Sinus Rhythm Database.** From these four databases, ECG records have been segmented at 4120 samples each forming 300 signals. They are normalized with mentioned gain for each database and are preprocessed with bandpass filters. MODWPT technique was used to obtain 54 features that are given as columns in .csv file that is uploaded here. So the file has 1200 x 54 size records.

In [1]:
## Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [2]:
ecg_data = pd.read_csv('ECGCvdata.csv')

In [3]:
ecg_data.head()

,RECORD,hbpermin,Pseg,PQseg,QRSseg,QRseg,QTseg,RSseg,STseg,Tseg,...,RMSSD,QRSarea,QRSperi,PQslope,QRslope,RSslope,STslope,NN50,pNN50,ECG_signal
0,1,74.925669,0.076508,0.108889,0.088254,0.043571,0.193016,0.044683,0.104762,0.130476,...,292.296636,18.457618,63.615239,-0.014364,0.075270,-0.070846,0.012606,2,5.882353,ARR
1,2,68.503469,0.072483,0.096181,0.093924,0.046267,0.193490,0.047656,0.099566,0.089149,...,318.563915,23.043230,67.787773,-0.021207,0.083773,-0.077458,0.016175,1,3.225806,ARR
2,3,83.488603,0.071154,0.086610,0.039530,0.018590,0.132479,0.020940,0.092949,0.094444,...,273.165412,10.756353,29.253827,-0.042542,NaN,NaN,0.027131,16,42.105263,ARR
3,4,68.503469,0.082812,0.108160,0.090365,0.045226,0.188802,0.045139,0.098437,0.088281,...,313.046941,23.845086,65.228737,-0.017806,0.091591,-0.088559,0.017022,2,6.451613,ARR
4,5,82.080000,0.070760,0.102632,0.101023,0.049415,0.193713,0.051608,0.092690,0.085965,...,263.225676,20.942791,72.830353,-0.016650,0.064547,-0.062246,0.016191,2,5.405405,ARR

In [4]:
ecg_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 56 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   RECORD      1200 non-null   int64
 1   hbpermin    1200 non-null   float64
 2   Pseg        1200 non-null   float64
 3   PQseg       1200 non-null   float64
 4   QRSseg      1200 non-null   float64
 5   QRseg       1200 non-null   float64
 6   QTseg       1200 non-null   float64
 7   RSseg       1200 non-null   float64
 8   STseg       1200 non-null   float64
 9   Tseg        1200 non-null   float64
 10  PTseg       1200 non-null   float64
 11  ECGseg      1200 non-null   float64
 12  QRtoQSdur   431 non-null    float64
 13  RStoQSdur   431 non-null    float64
 14  RRmean      1200 non-null   float64
 15  PPmean      1200 non-null   float64
 16  PQdis       1200 non-null   float64
 17  PonQdis     1200 non-null   float64
 18  PRdis       1200 non-null   float64
 19  PonRdis     1200 non-null   float64
 20  PSdis       1200 non-null   float64
 21  PonSdis     1200 non-null   float64
 22  PTdis       1200 non-null   float64
 23  PonTdis     1200 non-null   float64
 24  PToffdis    1200 non-null   float64
 25  QRdis       1200 non-null   float64
 26  QSdis       1200 non-null   float64
 27  QTdis       1200 non-null   float64
 28  QToffdis    1200 non-null   float64
 29  RSdis       1200 non-null   float64
 30  RTdis       1200 non-null   float64
 31  RToffdis    1200 non-null   float64
 32  STdis       1200 non-null   float64
 33  SToffdis    1200 non-null   float64
 34  PonToffdis  1200 non-null   float64
 35  PonPQang    643 non-null    float64
 36  PQRang      432 non-null    float64
 37  QRSang      431 non-null    float64
 38  RSTang      431 non-null    float64
 39  STToffang   774 non-null    float64
 40  RRTot       1200 non-null   int64
 41  NNTot       1200 non-null   int64
 42  SDRR        1200 non-null   float64
 43  IBIM        1200 non-null   float64
 44  IBISD       1200 non-null   float64
 45  SDSD        1200 non-null   float64
 46  RMSSD       1200 non-null   float64
 47  QRSarea     1200 non-null   float64
 48  QRSperi     1200 non-null   float64
 49  PQslope     1200 non-null   float64
 50  QRslope     432 non-null    float64
 51  RSslope     431 non-null    float64
 52  STslope     1200 non-null   float64
 53  NN50        1200 non-null   int64
 54  pNN50       1200 non-null   float64
 55  ECG_signal  1200 non-null   object
dtypes: float64(51), int64(4), object(1)
memory usage: 525.1+ KB

In [6]:
ecg_data['ECG_signal'].value_counts()

ECG_signal
ARR    300
AFF    300
CHF    300
NSR    300
Name: count, dtype: int64

In [7]:
ecg_data.describe()

,RECORD,hbpermin,Pseg,PQseg,QRSseg,QRseg,QTseg,RSseg,STseg,Tseg,...,SDSD,RMSSD,QRSarea,QRSperi,PQslope,QRslope,RSslope,STslope,NN50,pNN50
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,...,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,432.000000,431.000000,1200.000000,1200.000000,1200.000000
mean,600.500000,81.893980,0.060902,0.078099,0.048238,0.024437,0.141541,0.023800,0.093303,0.102714,...,42.484060,199.417894,7.675047,23.915846,-0.071647,0.141737,-0.150496,0.041659,6.442500,8.112425
std,346.554469,19.324351,0.009453,0.019897,0.034649,0.017501,0.029225,0.017175,0.013332,0.022594,...,105.722123,112.292014,8.452832,25.070324,0.049705,0.073086,0.077532,0.026456,7.748445,10.325033
min,1.000000,12.857143,0.021556,0.044526,0.000000,0.000000,0.098761,0.000000,0.052338,0.034936,...,0.800624,61.711281,0.000000,0.000000,-0.219938,0.028660,-0.315525,0.008183,0.000000,0.000000
25%,300.750000,67.563000,0.053943,0.060344,0.015101,0.007804,0.116016,0.007143,0.089423,0.090046,...,4.060951,123.147741,0.000000,0.124186,-0.106660,0.082613,-0.240304,0.023853,1.000000,0.613497
50%,600.500000,79.872000,0.060642,0.075184,0.044692,0.022676,0.137019,0.021965,0.097825,0.099210,...,11.265829,183.603851,5.228299,19.904060,-0.058518,0.108418,-0.116241,0.034460,3.000000,3.680982
75%,900.250000,96.000000,0.066849,0.095190,0.083032,0.041915,0.166314,0.041097,0.101200,0.112408,...,44.785825,248.101035,14.355389,46.194325,-0.027685,0.229659,-0.087565,0.049778,10.000000,12.883436
max,1200.000000,160.500000,0.095317,0.145577,0.120160,0.065278,0.211111,0.058333,0.138444,0.198413,...,1725.927603,1478.488460,33.131007,86.577082,-0.005427,0.270786,-0.027983,0.164633,37.000000,52.727273

In [8]:
ecg_data.duplicated().sum()

0

In [9]:
ecg_data.isnull().sum()

RECORD          0
hbpermin        0
Pseg            0
PQseg           0
QRSseg          0
QRseg           0
QTseg           0
RSseg           0
STseg           0
Tseg            0
PTseg           0
ECGseg          0
QRtoQSdur     769
RStoQSdur     769
RRmean          0
PPmean          0
PQdis           0
PonQdis         0
PRdis           0
PonRdis         0
PSdis           0
PonSdis         0
PTdis           0
PonTdis         0
PToffdis        0
QRdis           0
QSdis           0
QTdis           0
QToffdis        0
RSdis           0
RTdis           0
RToffdis        0
STdis           0
SToffdis        0
PonToffdis      0
PonPQang      557
PQRang        768
QRSang        769
RSTang        769
STToffang     426
RRTot           0
NNTot           0
SDRR            0
IBIM            0
IBISD           0
SDSD            0
RMSSD           0
QRSarea         0
QRSperi         0
PQslope         0
QRslope       768
RSslope       769
STslope         0
NN50            0
pNN50           0
ECG_signal      0
dtype: int64

## Data Preprocessing